// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ActualizarEntidadMascotas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActualizarEntidadMascotas));
        
        string IMigrationMetadata.Id
        {
            get { return "201612261829113_Actualizar Entidad Mascotas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
